@startjson incidence02
{
  "incidence": {
    "title": "Incident radiation",
    "description": "Incident radiation on a sample. It consists of the direction of irradiance, polarization, wavelengths and range of wavelengths.",
    "type": "object",
    "properties": {
      "direction": {
        "oneOf": [
        {
          "description": "Direction of incidence in a spherical coordinate system according to [ISO 80000-2:2019, Quantities and units - Part 2: Mathematics](https://www.iso.org/standard/64973.html).",
          "type": "object",
          "properties": {
            "polar": {
              "$ref": "number.json#/$defs/degreeBetweenZeroAndNinetyWithUncertainty",
              "description": "The polar angle is the angle between the direction of incidence and an axis which is perpendicular to the surface of the sample. It can have values between 0° and 90°. A polar angle of 0° means that the direction of incidence is perpendicular to the sample. A polar angle of 90° means that the direction of incidence is parallel to the sample. If the sample has `azimuthalAngleInvariance`, then the optical results depend only on the polar angle and not on the azimuth angle. If the sample has a `profileAngle` symmetry whose direction is equal to the prime direction, then the profile angle can be calculated from the polar and azimuth angles."
            }
            ,
            "azimuth": {
              "$ref": "number.json#/$defs/degreeBetweenZeroAndThreeHundredSixtyWithUncertainty",
              "description": "The direction of incidence is projected to the plane of the surface of the sample. The azimuth is the angle between this projection and the prime direction defined at `#/$defs/componentCharacteristics/properties/definitionOfSurfacesAndPrimeDirection`. It can have values between 0° and 360°. If we look at the sample as if it was a clock, the prime direction being 12 o'clock and the projection 11 o'clock, then the azimuth equals 30° because of the right-handed coordinate system of [ISO 80000-2:2019, Quantities and units - Part 2: Mathematics](https://www.iso.org/standard/64973.html)."
            }
          }
          ,
          "additionalProperties": false,
          "required": ["polar"]
        }
        ,
        {
          "title": "Hemispherical",
          "description": "Incidence arrives from all directions of the hemisphere on the sample surface.",
          "type": "string",
          "const": "hemispherical"
        }
        ]
      }
      ,
      "wavelengths": {
        "oneOf": [
        {
          "title": "Uncertain wavelength",
          "type": "object",
          "properties": {
            "wavelength": {
              "$ref": "number.json#/$defs/nanometer",
              "description": "One wavelength in nanometers. If necessary, its uncertainty can be specified with `uncertainty`."
            }
            ,
            "uncertainty": { "$ref": "#/$defs/wavelengthUncertainty" }
          }
          ,
          "additionalProperties": false,
          "required": ["wavelength"]
        }
        ,
        {
          "title": "Integral over wavelengths",
          "description": "Tells that the corresponding result is an integral with a certain spectrum over wavelengths.",
          "type": "object",
          "properties": {
            "integral": {
              "type": "string",
              "enum": ["infrared", "solar", "ultraviolet", "visible", "other"],
              "description": "Spectrum over which the integral result was measured or calculated. `ultraviolet`, `visible`, `solar` and `infrared` indicate the range of the wavelengths used for the integral values. Details about the spectrum are provided by the method which has been applied to generate the data set. If neither `ultraviolet`, `visible`, `solar` and `infrared` describe the spectrum correctly, `other` indicates that all information about the spectrum is provided by the applied method."
            }
          }
          ,
          "additionalProperties": false,
          "required": ["integral"]
        }
        ]
      }
      ,
      "polarization": {
        "title": "Polarization",
        "description": "Polarization is a characteristic of radiation which in general influences transmittance and reflectance. Radiation can be polarized linearly and circularly.",
        "oneOf": [
        {
          "title": "Linear polarization",
          "type": "object",
          "properties": {
            "s": {
              "$ref": "number.json#/$defs/numberWithUncertainty",
              "description": "Fraction of radiation with electric field perpendicular to the plane of incidence of the radiation on the sample. It is in theory between `0` and `1` inclusive. However, in measurement data because of uncertainty it is between `0 - uncertainty` and `1 + uncertainty` inclusive."
            }
            ,
            "p": {
              "$ref": "number.json#/$defs/numberWithUncertainty",
              "description": "Fraction of radiation with electric field parallel to the plane of incidence of the radiation on the sample. It is in theory between `0` and `1` inclusive. However, in measurement data because of uncertainty it is between `0 - uncertainty` and `1 + uncertainty` inclusive."
            }
          }
          ,
          "additionalProperties": false,
          "required": ["s", "p"]
        }
        ,
        {
          "title": "Circular polarization",
          "description": "`leftHanded` means that the radiation is circularly polarized and rotates in a left-hand sense with respect to the direction of radiation. `rightHanded` means that the radiation is circularly polarized and rotates in a right-hand sense with respect to the direction of radiation.",

          "type": "string",
          "enum": ["leftHanded", "rightHanded"]
        }
        ]
      }
    }
    ,
    "additionalProperties": false,
    "required": ["direction", "wavelengths"]
  }
}
@endjson