@startjson opticalDataPointSchema
{
  "dataPoint": {
    "oneOf":
    {
      "incidence": {
        "direction": {
          "oneOf":
          {
            "polar": {
              "number": "degreeBetweenZeroAndNinetyWithUncertainty"
            }
            ,
            "azimuth": {
              "number": "degreeBetweenZeroAndThreeHundredSixtyWithUncertainty"

            }
          }
          ,
          "":
          {
            "type": "string",
            "const": "hemispherical"
          }

        }
        ,
        "wavelengths": {
          "oneOf":
          {
            "wavelength": {
              "number": "nanometer"
            }
            ,
            "uncertainty": [ "bandwidth", "amplificationFactor" ]
          }
          ,
          "":
          {
            "integral": ["infrared", "solar", "ultraviolet", "visible", "other"]
          }

        }
        ,
        "polarization": {
          "oneOf":
          {
            "s": {
              "number": "numberWithUncertainty"
            }
            ,
            "p": {
              "number": "numberWithUncertainty"
            }
          }
          ,
          "":
          {
            "Circular polarization": ["leftHanded", "rightHanded"]
          }

        }
      }
      ,
      "componentCharacteristics": {
        "treatmentBefore": {
          "common": "reference"
        }
        ,
        "locationOnSample": {
          "common": "reference"
        }
        ,
        "polarizationSensitivity": {
          "common": "reference"
        }
        ,
        "instrumentSignature": {
          "number": "nonNegativeNumber"
        }
        ,
        "normalization":  ["absolute", "relative", "specular", "diffuseReflectance"]
        ,
        "referenceSample": {
          "common": "reference"
        }
        ,
        "spot": {
          "common": "reference"
        }
        ,
        "slatTilt": {
          "common": "angles/slatTilt"
        }
        ,
        "symmetries": [
        "azimuthalAngleInvariance",
        "profileAngle",
        "mirror",
        "rotationalDependingOnAzimuth",
        "mirrorAndRotational"
        ]
        ,
        "surface": {
          "component": "surface"
        }
      }
      ,
      "emergence": {
        "direction": {
          "oneOf":
          {
            "polar": {
              "number": "degreeWithUncertainty"
            }
            ,
            "azimuth": {
              "number": "degreeWithUncertainty"
            }
          }
          ,
          "":
          {
            "string": ["diffuse", "hemispherical"]
          }

        }
      }
      ,
      "results": {
        "transmittance": {
          "number": "numberWithUncertainty"
        }
        ,
        "reflectance": {
          "number": "numberWithUncertainty"
        }
        ,
        "absorptanceEmittance": {
          "number": "numberWithUncertainty"
        }
      }
    }
    ,
    "":
    {
      "name": {
        "type": "string"
      }
      ,
      "cielabColors":
      {
        "lStar": {
          "number": "numberWithUncertainty"
        }
        ,
        "aStar": {
          "number": "numberWithUncertainty"
        }
        ,
        "bStar": {
          "number": "numberWithUncertainty"
        }
        ,
        "direction":  ["reflection", "transmission"]
        ,
        "surface": {
          "component": "surface"
        }
        ,
        "observer":  ["twoDegrees", "tenDegrees"]
        ,
        "illuminant":  ["A", "D65"]
      }
      ,
      "colorRenderingIndices": {
        "value": {
          "number": "numberWithUncertainty"
        }
        ,
        "direction":  ["reflection", "transmission"]
        ,
        "surface": {
          "component": "surface"
        }
      }
    }

  }
}
@endjson